import { Nav } from "@/components/nav";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(" overflow-y-scroll", inter.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
